INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Amanda', 'Nutricionista', 2000, 'Idosos', 'Santos', 29 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Cobe', 'Eletricista', 1800, 'Geral', 'Santos', 30);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Fábio', 'Cozinheiro', 1500, 'Idosos', 'São Vincente', 28);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Cristian', 'Faxineiro', 1200, 'Geral',  'Paripiranga', 27);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Carlos', 'Treinador', 3000, 'Jovens', 'Simão Dias', 32 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Nami', 'Boxeadora', 2200, 'Jovens', 'Paripiranga',  40);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Robin', 'Médica', 7000, 'Geral', 'São Vincente', 38 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Sanji', 'Enfermeiro', 3600, 'Geral', 'São Vincente', 29 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Zoro', 'Atendente', 2000, 'Geral', 'Simão Dias', 37 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Brook', 'Gerente', 5800, 'Geral', 'Paripiranga' , 43 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Tanjiro', 'Supervisor de lutas', 5000, 'Jovens', 'Santos', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Erza', 'Diretora', 8000, 'Geral', 'Simão Dias', 55);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Lucy', 'Supervisora aquática', 4300, 'Crianças', 'Lagarto', 37 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Juvia', 'Supervisora de musculação', 3400, 'Idosos', 'Paripiranga', 54 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Nezuko', 'Professora', 2220, 'Crianças', 'Lagarto', 31 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Violet', 'Avaliadora física', 2060, 'Idosos', 'Lagarto', 29);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Viola', 'Orientadora', 3550, 'Crianças', 'Lagarto', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Faustão', 'Contador', 2304, 'Geral', 'São Vincente',28 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Felipe', 'Contador', 2304, 'Geral', 'Lagarto', 35 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Rodrigo', 'Professor', 2220, 'Idosos', 'Lagarto', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Felix', 'Boxeador', 2200, 'Jovens', 'Paripiranga', 22 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Jimin', 'Médico', 7000, 'Geral', 'Lagarto', 67 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Carol', 'Enfermeira', 3600, 'Geral', 'Santos', 34 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Eduardo', 'Nutricionista', 2000,'Geral' , 'Lagarto', 24 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Julian', 'Psicólogo', 3000, 'Geral', 'São Vincente', 34 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Muzan', 'Fisioterapeuta', 3100, 'Geral', 'Santos', 30 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Moana', 'Psicóloga', 3000, 'Crianças', 'Lagarto', 27 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Kate', 'Eletricista', 1800, 'Geral', 'Simão Dias', 31 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Noah', 'Cozinheiro', 1500, 'Geral', 'Lagarto', 20 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Vitor', 'Faxineiro', 1200, 'Geral', 'Simão Dias', 27 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Josh', 'Faxineiro', 1200, 'Geral', 'São Vincente', 27);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Savana', 'Cozinheira', 1500, 'Geral', 'São Vincente', 29);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Shivani', 'Treinadora', 3000, 'Crianças', 'São Vincente', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Sofia', 'Boxeadora', 2200, 'Crianças', 'Simão Dias', 42);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Hina', 'Supervisora aquática', 4300, 'Crianças', 'Paripiranga', 28);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Sina', 'Supervisora de lutas', 5000, 'Idosos', 'Lagarto', 37 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Nour', 'Supervisora de lutas', 5000, 'Crianças', 'Santos', 38 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Lamar', 'Supervisor de musculação', 3400, 'Idosos', 'Simão Dias', 32 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Maxuel', 'Dentista', 6600, 'Geral', 'Lagarto', 35 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Camila', 'Contadora', 2304, 'Geral', 'São Vincente', 36 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Renata', 'Atendente', 2000, 'Geral', 'Lagarto', 22 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Ava', 'Policial', 5000, 'Geral', 'Simão Dias', 21 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Adam', 'Avaliador Físico', 2060, 'Jovens', 'Lagarto', 26);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Leon', 'Mecânico', 3111, 'Geral', 'São Vincente', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Leonardo', 'Policial', 5000, 'Geral', 'Santos', 27 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Alana', 'Policial', 5000, 'Geral', 'Paripiranga', 28);
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Mateus', 'Vigia', 2800, 'Geral', 'Santos', 30 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Jeferson', 'Vigia', 2800, 'Geral', 'Lagarto', 20 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Edelvânia', 'Vigia', 2800, 'Geral', 'Simão Dias', 26 );
INSERT INTO "Academia".profissionais(nome, profissao, salario, categoria, endereco, idade) VALUES ('Asta', 'Policial', 5000, 'Geral', 'São Vincente', 30 );